version: 1.0

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Build started on `date`
      - mvn clean
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package -DskipTest=true
artifacts:
  files:
    - target/scheduler.jar
cache:
  path:
    - '/root/.m2/**/*'
