spring:
  datasource:
    hikari:
      username: oddi
      password: "oddi1@#"
      pool-name: oddiad-pool
      max-lifetime: 12000
      connection-test-query: select now()
      minimum-idle: 2
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: "jdbc:mysql://ls-a2834d111b7d0d1385ca4360b6718cf409b75eff.cvxedmimklz0.ap-northeast-2.rds.amazonaws.com:3306/oddi_ad?characterEncoding=utf8&useSSL=false"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults=false: false
      globally_quoted_identifiers: true
logging:
  config: classpath:logback-file.xml


notification:
  sender-phone: "01051227638"

oddi:
  user-web-host: "http://oddiad.nextnow.kr"
  manager-web-host: "http://oddiad.portal.nextnow.kr"
  user-web-voc-detail: "/inquire"

aws:
  s3:
    public:
      bucket: "skd-s3"
      video-dir: "/oddiad/adv/pre-convert"
      url-host: "https://skd-s3.s3.ap-northeast-2.amazonaws.com"
      region: ap-northeast-2
  media:
    host: "https://skd-s3.s3.ap-northeast-2.amazonaws.com/oddiad/adv/converted/"
    role-arn: "arn:aws:iam::734578097671:role/service-role/MediaConvert_Default_Role"
    file-out-dir: "/oddiad/adv/converted"
    end-point: "https://mlboolfjb.mediaconvert.us-west-2.amazonaws.com"
    region: us-west-2


device-api: "http://oddiad-api.video.nextnow.kr"

