spring:
  datasource:
    hikari:
      username: ODDI_APP
      password: "app21_oddiXX"
      pool-name: oddi-cp
      max-lifetime: 12000
      connection-test-query: select now()
      minimum-idle: 2
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: "jdbc:mysql://rds-an2-oddiad-prd-mysql.ca3pv7invojs.ap-northeast-2.rds.amazonaws.com:3310/oddi?characterEncoding=utf8&useSSL=false"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults=false: false
      globally_quoted_identifiers: true
logging:
  config: classpath:logback-op.xml

notification:
  sender-phone: "01075633127"

oddi:
  user-web-host: "https://oddiad.co.kr"
  manager-web-host: "https://portal.oddiad.co.kr"
  user-web-voc-detail: "/inquire"

aws:
  s3:
    public:
      bucket: "s3-an2-oddiad-prod"
      video-dir: "/adv/pre-convert"
      url-host: "https://resource.oddiad.co.kr/"
      region: ap-northeast-2
  media:
    host: "https://resource.oddiad.co.kr/adv/converted/"
    role-arn: "arn:aws:iam::604329123335:role/role-oddiad-mediaconvert"
    file-out-dir: "/adv/converted"
    end-point: "https://bnklbqvoa.mediaconvert.ap-northeast-2.amazonaws.com"
    region: ap-northeast-2


device-api: "https://device.oddiad.co.kr/"


decorator:
  datasource:
    p6spy:
      enable-logging: false
      multiline: false
